version: "3.2"
services:
  #RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    container_name: rabbitmq
    networks:
      say-crm:
        aliases:
          - say-crm
  #MySQL
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
networks:
  say-crm:
    driver: bridge
volumes:
  db_data: {}